### ISSUE TITLE
Enjoying meetup.com's social features (RSVP)

### ISSUE THREAD

**Issue by mightyiam** [jsIsrael/goodness-squad#1]
https://github.com/jsIsrael/goodness-squad/blob/master/how-to-organize-an-event.md#2-logistics

I quite like the social features of Meetup.com. Would it be possible to somehow use the RSVP of meetup.com and still enjoy the benefits of the google form? Or, what about importing the RSVP from the form spreadsheet into the meetup?

**Comment by shairez** [comment]
We are working out a way to integrate tools (gitter) to create a more social experience.

**Comment by mightyiam** [comment]
I appreciate it.
